Add instructions for setting up integration tests
Original question:

This page, 
[ember-cli testing](http://iamstef.net/ember-cli/#testing),
 says "The included tests demonstrate how to write both unit tests and acceptance/integration tests using the new 
[ember-testing package](http://ianpetzer.wordpress.com/2013/06/14/getting-started-with-integration-testing-ember-js-using-ember-testing-and-qunit-rails/)."

However in order to get an integration test working, I need to find `module` and `visit` or any of the [ember test helpers](http://emberjs.com/guides/testing/test-helpers/).
Where are they found, where can I import them from?


----

Details:

The closest I have found to `module` is `moduleFor`, which can be imported from `ember-qunit`. Module for is not suitable for integration testing as I am testing an entire page or series of pages within the app, rather than an individual model, route, controller, view, etc.

My best guess is that `visit` can be found within Ember itself, but I am not sure where to import it from.

Using neither `module` nor `moduleFor`, I am able to run the tests, but they error out:

> ReferenceError: visit is not defined




---

See [question on SO](http://stackoverflow.com/questions/24010529/setting-up-integration-tests-in-an-ember-cli-app-how-to-access-module-and-vi)