Use fs-extra's `ensureDir` to avoid race condition in `mk-tmp-dir-in`.
CI is somewhat plagued by random race conditiony failure for the
following test:

```
not ok 153 Blueprint basic blueprint installation "before each" hook for "calls appropriate hooks with correct arguments"
  Error: EEXIST: file already exists, mkdir '/home/travis/build/ember-cli/ember-cli/tmp'
```

This removes some crufty code (`fs.exists` has been deprecated for a
while) in favor of using a nice convenience method from `fs-extra`.

I am not 100% certain this "solves the race condition", but it seems
like a nice bit of cleanup/refactoring regardless...