Wrapped error prone require in try/catch block
Because the build file is user editable, it presents the possibility of a user introducing invalid javascript, which causes `require` to throw an error.

I would like the error message to be more descriptive, but I couldn't get any more information from the exception require() threw.

Also I was debating whether to use the full path, `buildFilePath`, or just the file name, `file`.

I encountered this because I forgot a comma, and `ember s` returned this error:
```
Unexpected string
SyntaxError: Unexpected string
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at module.exports (/Users/michael/Sites/myemberapp/node_modules/ember-cli/lib/utilities/find-build-file.js:20:21)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/michael/Sites/myemberapp/node_modules/ember-cli/lib/models/builder.js:49:21)
    at Class.module.exports.Task.extend.init (/Users/michael/Sites/myemberapp/node_modules/ember-cli/lib/models/builder.js:89:10)
```
Which this makes no sense.

Now the error message will be:
```
Error: could not require "ember-cli-build.js": Unexpected string
Error: Error: could not require "ember-cli-build.js": Unexpected string
    at module.exports (/Users/michael/Sites/myemberapp/node_modules/ember-cli/lib/utilities/find-build-file.js:24:8)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/michael/Sites/myemberapp/node_modules/ember-cli/lib/models/builder.js:49:21)
    at Class.module.exports.Task.extend.init (/Users/michael/Sites/myemberapp/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/Users/michael/Sites/myemberapp/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/michael/Sites/myemberapp/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /Users/michael/Sites/myemberapp/node_modules/ember-cli/lib/commands/serve.js:70:22
    at lib$rsvp$$internal$$tryCatch (/Users/michael/Sites/myemberapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/michael/Sites/myemberapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at /Users/michael/Sites/myemberapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/Users/michael/Sites/myemberapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

While the stack trace doesn't help the user, at least I know the error is in `ember-cli-build.js`.